name: Decompress, Install Dependencies and Run


on:
  push:
    branches:
      - main  # أو أي فرع آخر تريد

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install p7zip
      run: sudo apt-get install -y p7zip-full

    - name: Decompress 7z file
      run: 7z x TogashiBot.7z -o${{ github.workspace }}/output_directory

    - name: Navigate to TogashiBot directory
      run: cd output_directory/TogashiBot

    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # يمكنك تغييره إلى '3.11' إذا كنت بحاجة لذلك

    - name: Install dependencies
      run: |
        cd output_directory/TogashiBot
        pip install -r requr.txt  # تأكد من أن اسم الملف صحيح

    - name: Run main.py
      run: |
        cd output_directory/TogashiBot
        python main.py
